### ISSUE TITLE
question 2 and 3

### ISSUE THREAD

**Issue by nbm5260** [khanimzul/stat297hw1#2]
can everyone email me your picture..i would prefer gmail. to make things easier, please send it to iffah all the details needed for "Group Members" section.

- [x] a picture
- [x] your favorite quote
- [x] state and describe your hobby
- [x] your classes for this semester as well as the time
please send to
nurlisafadli@gmail.com
iffahmsaufi@gmail.com

if anyone has any suggestion, please let me know..

**Comment by shafiqahazman96** [comment]
I submitted mine.
